### ISSUE TITLE
Idempotent configuration commands

### ISSUE THREAD

**Issue by dpwrussell** [openmicroscopy/openmicroscopy#4597]
During our recent ansible configuration of OMERO I had to do some less than desirable things to make it work because some of the configuration can not be done idempotently.

Examples:

When configuring `omero.web.ui.top_links` it is not possible to use `append` because this will result in (after multiple runs) repeated entries, so instead it is necessary to use `set` which necessitates specifying all of the defaults (which could easily change with a new OMERO version).
```yaml
omero.web.ui.top_links: '[["Data", "webindex", {"title": "Browse Data via Projects, Tags etc"}],["History", "history", {"title": "History"}],["Help", "http://help.openmicroscopy.org/", {"title": "Open OMERO user guide in a new tab", "target": "new"}],["Figure", "figure_index"],["Tag Search", "tagsearch"]]'
```

I think the best solution to this could be a new command `exists` for things which are lists.

For the `omero.web.ui.top_links` example:
```bash
omero config exists omero.web.ui.top_links '["Figure", "figure_index"]'
omero config exists omero.web.ui.top_links '["Tag Search", "tagsearch"]'
```

This one could probably be configured by manipulating XML instead, but as that is not the recommended way to do these changes then I think this makes more sense. Here is another example which could not be done that way though.

Plugin scripts are installed with `upload` and then replaced with `replace`. This is fine when doing things manually, but when using config management, it has no way of knowing what to do. If you run `upload` every time this results in the original script not being replaced. On the flip side, even if the script is already installed, it can't be replaced without some nasty bash foo to get the ID.

``` yaml

- name: check if figure script has been installed (database)
  shell: "{{ omero_base }}/OMERO.server/current/bin/omero -u root -w {{ omero_root_password }} -s localhost script list | grep 'Figure_To_Pdf' | gawk -F '|' '{ print $1 }'"
  sudo: yes
  sudo_user: "{{ omero_user }}"
  register: figure_script_id

# Install the figure script (only the first time)
- name: load plugin scripts (first time)
  shell: "{{ omero_base }}/OMERO.server/current/bin/omero -u root -w {{ omero_root_password }} -s localhost script upload omero/figure_scripts/Figure_To_Pdf.py --official"
  sudo: yes
  sudo_user: "{{ omero_user }}"
  args:
    chdir: "{{ omero_base }}/OMERO.web/current/lib/python/omeroweb/figure/scripts/"
  when: figure_script_id.stdout == ""

# Always reinstall the figure script (unless this was the first time)
- name: load plugin scripts (subsequent times)
  shell: "{{ omero_base }}/OMERO.server/current/bin/omero -u root -w {{ omero_root_password }} -s localhost script replace {{ figure_script_id.stdout }} omero/figure_scripts/Figure_To_Pdf.py"
  sudo: yes
  sudo_user: "{{ omero_user }}"
  args:
    chdir: "{{ omero_base }}/OMERO.web/current/lib/python/omeroweb/figure/scripts/"
  when: figure_script_id.stdout != ""
```

I'm not certain what the best way to fix that one is. Perhaps a command that is not based on ID like `replace_or_install_script_at_location` or something.

It would be really nice to be able to have any idempotent commands return values be such that config management could determine if something has `changed` or not.

Finally, if Ansible is what we are all using, then perhaps an [action plugin or module](http://ndemengel.github.io/2015/01/20/ansible-modules-and-action-plugins/) could be developed (perhaps making use of underlying idempotent commands with nice return types) so that one could do something like:

```yaml
- name: Add OMERO.figure to web top links
  omero_config:
    key: 'omero.web.config.ui.top_links'
    value: '["Figure", "figure_index"]'
    state: present
```
